---
abstract: 'Be like ABHIISNOT'
author:
  - 'Abhishek Shende <abhishekisnot@gmail.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.024
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-ABHIISNOT
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Dist::Zilla: 0
  ExtUtils::MakeMaker: 0
  Log::Contextual: 0
  Log::Log4perl: 0
  perl: 5.014002
resources:
  bugtracker: https://github.com/abhishekisnot/Task-BeLike-ABHIISNOT/issues
  homepage: https://github.com/abhishekisnot/Task-BeLike-ABHIISNOT
  repository: https://github.com/abhishekisnot/Task-BeLike-ABHIISNOT.git
version: 0.01
